apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ourapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ourapp
  minReplicas: 1
  # 5 реплик чтобы был не большой запас.
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
